levstik/urls.py
from django.urls import include, path

from levstik.views.home import HomeView, AboutUs
from levstik.views.profile import ProfileView
from levstik.views.register import RegisterView
from levstik.views.winner import CreateWinnerView, EditWinnerView
from levstik.views.winner_profile import WinnerProfileView
from levstik.views.winners import WinnersView


urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('', include('django.contrib.auth.urls')),
    path('about-us/', AboutUs.as_view(), name="about_us"),
    path('register/', RegisterView.as_view(), name="register"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('winner/', CreateWinnerView.as_view(), name="create_winner"),
    path('winner/<int:id>/edit/', EditWinnerView.as_view(), name="edit_winner"),
    path('winner/<slug:slug>/', WinnerProfileView.as_view(), name="winner_profile"),
    path('winners/', WinnersView.as_view(), name="winners"),
]

levstik_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('levstik.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

levstik/models/winner.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from django.template.defaultfilters import filesizeformat


def max_file_size(image):
    if image.size > settings.MAX_UPLOAD_SIZE:
        raise ValidationError('File too large. Size should not exceed {}.'.format(filesizeformat(settings.MAX_UPLOAD_SIZE)))


def file_path(instance, filename):
    ext = filename.split('.')[-1]
    return 'images/{}.{}'.format(instance.slug_name, ext)


class Winner(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    birth_date = models.DateTimeField()
    awarded_date = models.DateTimeField()
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to=file_path, default='images/default_image.jpg', validators=[max_file_size])

    created_by = models.ForeignKey(User, on_delete=models.PROTECT)

    deleted = models.DateTimeField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-awarded_date',)

    @property
    def full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    @property
    def slug_name(self):
        return slugify(self.full_name)

    @property
    def slug_title(self):
        return "{}-{}".format(self.id, slugify(self.full_name))

    @property
    def url(self):
        return "http://{}/winner/{}/".format(settings.BASE_URL, self.slug_title)

levstik/views/winner.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic.base import View

from levstik.forms.create_winner_form import CreateWinnerForm
from levstik.models import Winner


class CreateWinnerView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        context = dict(
            form=CreateWinnerForm()
        )

        return render(request, "winners/winner_create.html", context)

    @staticmethod
    def post(request):
        user = request.user
        form = CreateWinnerForm(request.POST, request.FILES, created_by=user)

        if form.is_valid():
            form.save()

            messages.success(request, "Nagrajenec je bil ustvarjen!")
            return HttpResponseRedirect(reverse('home'))

        context = dict(
            form=form
        )

        return render(request, "winners/winner_create.html", context)


class EditWinnerView(LoginRequiredMixin, View):
    @staticmethod
    def get(request, id):
        winner = get_object_or_404(Winner, id=id)
        context = dict(
            form=CreateWinnerForm(instance=winner)
        )

        return render(request, "winners/winner_edit.html", context)

    @staticmethod
    def post(request, id):
        user = request.user
        winner = get_object_or_404(Winner, id=id)
        form = CreateWinnerForm(instance=winner, data=request.POST, files=request.FILES, created_by=user)

        if form.is_valid():
            form.save()
            messages.success(request, "Nagrajenec je bil posodobljen!")
            return HttpResponseRedirect(reverse('winner_profile', args=[id]))

        context = dict(
            form=form
        )

        return render(request, "winners/winner_create.html", context)

levstik/views/winner_profile.py
from django.views.generic.base import View
from django.shortcuts import render, get_object_or_404
from django.http import Http404

from levstik.models import Winner


class WinnerProfileView(View):

    @staticmethod
    def get(request, slug):
        try:
            winner_id = int(slug.split('-')[0])
        except ValueError:
            raise Http404()

        winner = get_object_or_404(Winner, id=winner_id)
        context = dict(
            winner=winner
        )

        template = "winners/winner_profile.html"
        return render(request, template, context)

levstik/views/winners.py
from django.views.generic.base import View
from django.shortcuts import render

from levstik.models.winner import Winner


class WinnersView(View):

    @staticmethod
    def get(request):
        context = dict(
            winners=Winner.objects.all()
        )
        return render(request, "levstik/winners.html", context)

templates/winners/winner_create.html
{% extends "base.html" %}
{% load static i18n humanize %}

{% block content %}
    <div class="container">
        <div class="row pt-3">
            <div class="col-md-8 offset-md-2">
                <div class="row">
                    <div class="col-12 mb-3 text-sm-left text-center">
                        <h2>Dodaj nagrajenca</h2>
                    </div>
                </div>
                <form class="form " action="{% url 'create_winner' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="card border-light">
                        <div class="card-body">
                            {% for field in form.visible_fields %}
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-8 offset-sm-2">
                                            <strong>
                                                {{ field.label_tag }}
                                            </strong>
                                            {{ field }}
                                            {{ field.errors }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-8 col-sm-6 mt-3 mb-3 offset-sm-6 offset-2">
                            <button class="nextButton btn btn-primary">
                                Dodaj nagrajenca
                            </button>
                        </div>
                    </div>
                </form>
            </div>

            </div>
        </div>
    </div>

{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/datetimepicker/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'js/datetimepicker/locales/sl.js' %}"></script>
    <script src="{% static 'plugins/filer/js/jquery.filer.js' %}"></script>

    <script type="text/javascript">
        $(function () {
            let options = {
                limit: 1,
                maxSize: 5,
                showThumbs: true
            };
            $("#id_image").filer( options );

            let now = new Date("{% now 'Y,n,j' %}");

            $('#id_birth_date, #id_awarded_date').datetimepicker({
                sideBySide: true,
                format: 'D. M. YYYY',
                locale: 'sl',
                viewMode: "years",
            });
        });

    </script>
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <link href="{% static 'plugins/filer/css/jquery.filer.css' %}" type="text/css" rel="stylesheet" />
    <link href="{% static 'plugins/filer/css/themes/jquery.filer-dragdropbox-theme.css' %}" type="text/css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css"
          integrity="sha256-bLNUHzSMEvxBhoysBE7EXYlIrmo7+n7F4oJra1IgOaM=" crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
    <style>
        body {
            background-color: #f4f4f4;
        }

        .jFiler-input {
            width: 100% !important;
        }

        .nextButton {
            min-height: 42px;
            width: 100%;
            border-radius: 3px;
            border-color: #4cb994;
            font-size: 16px;
            font-weight: 600;
            text-align: center;
            color: #ffffff;
            -webkit-appearance: none;
            background-repeat: no-repeat;
            background-size: 9px 14px;
            background-position: right 13px center;
            transition: .5s;
        }
    </style>
{% endblock %}

{% block footer %}{% endblock %}

templates/winners/winner_edit.html
{% extends "base.html" %}
{% load static i18n humanize %}

{% block content %}
    <div class="container">
        <div class="row pt-3">
            <div class="col-md-8 offset-md-2">
                <div class="row">
                    <div class="col-12 mb-3 text-sm-left text-center">
                        <h2>Uredi nagrajenca</h2>
                    </div>
                </div>
                <form class="form " action="{% url 'edit_winner' form.instance.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="card border-light">
                        <div class="card-body">
                            {% for field in form.visible_fields %}
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-8 offset-sm-2">
                                            <strong>
                                                {{ field.label_tag }}
                                            </strong>
                                            {{ field }}
                                            {{ field.errors }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-8 col-sm-6 mt-3 mb-3 offset-sm-6 offset-2">
                            <button class="nextButton btn btn-primary">
                                Shrani
                            </button>
                        </div>
                    </div>
                </form>
            </div>

            </div>
        </div>
    </div>

{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/datetimepicker/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'js/datetimepicker/locales/sl.js' %}"></script>
    <script src="{% static 'plugins/filer/js/jquery.filer.js' %}"></script>

    <script type="text/javascript">
        $(function () {
            let options = {
                limit: 1,
                maxSize: 5,
                showThumbs: true
            };
            $("#id_image").filer( options );

            $('#id_birth_date, #id_awarded_date').datetimepicker({
                sideBySide: true,
                format: 'D. M. YYYY',
                locale: 'sl',
                viewMode: "years",
            });
        });

    </script>
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <link href="{% static 'plugins/filer/css/jquery.filer.css' %}" type="text/css" rel="stylesheet" />
    <link href="{% static 'plugins/filer/css/themes/jquery.filer-dragdropbox-theme.css' %}" type="text/css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css"
          integrity="sha256-bLNUHzSMEvxBhoysBE7EXYlIrmo7+n7F4oJra1IgOaM=" crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
    <style>
        body {
            background-color: #f4f4f4;
        }

        .jFiler-input {
            width: 100% !important;
        }

        .nextButton {
            min-height: 42px;
            width: 100%;
            border-radius: 3px;
            border-color: #4cb994;
            font-size: 16px;
            font-weight: 600;
            text-align: center;
            color: #ffffff;
            -webkit-appearance: none;
            background-repeat: no-repeat;
            background-size: 9px 14px;
            background-position: right 13px center;
            transition: .5s;
        }
    </style>
{% endblock %}

{% block footer %}{% endblock %}

templates/winners/winner_profile.html
{% extends "base.html" %}

{% load static i18n %}

{% block content %}
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

    <img class="avatar-image rounded-circle img-fluid" src="{{ winner.image.url }}" alt="">
    <h1 class="display-4 cursive">
        {{ winner.full_name }}
    </h1>
    {%  if user.is_authenticated %}
        <div class="mb-4">
            <a href="{% url 'edit_winner' winner.id %}" class="btn btn-primary">Uredi nagrajenca</a>
        </div>
    {% endif %}
    <div class="timeline-panel">
        <div class="timeline-heading">
            <h5 class="text-muted">{{ winner.awarded_date|date:"F Y" }}</h5>
        </div>
        <div class="timeline-body">
            <p class="text-muted">{{ winner.description }}</p>
        </div>
    </div>
    {% if profile.description %}
        <p class="lead">{{ profile.description }}</p>
    {% endif %}
</div>

<!-- Modal -->
<div class="modal fade" id="avatarModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="fas fa-times"></i>
            </button>
            <div class="modal-body p-0 mx-auto">
                <img src=""  id="avatarModalImg" alt="Slika nagrajenca">
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script>
        $('.avatar-image').click(function showModal() {
            console.log($(this)[0].src);
            $('#avatarModalImg').attr('src', $(this)[0].src);
            $('#avatarModal').modal('show');
        });
    </script>
{% endblock %}


{% block extra_css %}
    {{ block.super }}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css"
          integrity="sha256-bLNUHzSMEvxBhoysBE7EXYlIrmo7+n7F4oJra1IgOaM=" crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">

    <style>
        .modal-content {
            width: auto !important;
            margin: auto;
        }

        .modal .close {
            position: absolute;
            right: 15px;
            top: 15px;
            z-index: 10;
            font-size: 2rem;
            font-weight: bold;
        }

        .avatar-image {
            vertical-align: middle;
            width: 350px;
            height: 350px;
            border-radius: 50%;
            object-fit: cover;
        }
    </style>
{% endblock %}